import "@/styles/globals.css";
import type { AppProps } from "next/app";
import localFont from "next/font/local";
import { Wallet } from "./Wallet";
import Head from "next/head";
import { Toaster } from 'sonner';

const geistSans = localFont({
  src: "/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Baby Swap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Wallet>
          <Component {...pageProps} />
          <Toaster
            position="top-right"
            toastOptions={{
              className: 'my-toast',
              style: {
                background: '#f0f0f0', // Light gray background
                color: 'black',
                border: '1px solid #f472b6', // Pink border to match your theme
                fontSize: '16px', // Larger font size
                padding: '15px',
              },
              // Specific styling for different toast types
              classNames: {
                error: 'toast-error',
                success: 'toast-success',
                warning: 'toast-warning',
              }
            }}
          />
          <style global jsx>{`
        .my-toast .toast-error {
          background: #fecaca !important; // Light red for errors
          color: #7f1d1d !important; // Dark red text
          border: 1px solid #f87171 !important;
        }
        .my-toast .toast-success {
          background: #dcfce7 !important; // Light green for success
          color: #14532d !important; // Dark green text
          border: 1px solid #4ade80 !important;
        }
        .my-toast .toast-warning {
          background: #fecaca !important; // Light red for warnings
          color: #7f1d1d !important; // Dark red text
          border: 1px solid #f87171 !important;
        }
      `}</style>
        </Wallet>
      </div>
    </>
  );
}
